### ISSUE TITLE
When unlinking data of a token, the character sheet top right link icon is not properly updated.

### ISSUE THREAD

**Issue by bobifle** [Bubz43/ep2e#1]
v 0.6765

When unlinking data of a token, the character sheet top right link icon is not properly updated.

How to reproduce:

- have a linked token on the canva
- close the sheet, then open it
- click on the top right token icon and unlink the token from its actor
- click on update token, the link icon on the open  character sheet is not updated

**Comment by Bubz43** [comment]
There were actually a couple bugs related to switching between linked/unlinked tokens, or with switching between different tokens linked to the same actor. The next release should have things work as expected.
