### ISSUE TITLE
Software skills dont actually make rolls even with autoroll selected

### ISSUE THREAD

**Issue by ava5627** [Bubz43/ep2e#10]
![image](https://github.com/user-attachments/assets/de4df4cd-ca3e-49f0-8962-04dfe1a14e5d)
![image](https://github.com/user-attachments/assets/508364b3-fe86-431d-b7fd-bebd192eff65)

**Comment by Bubz43** [comment]
Fixed in `1.2.11`, think this was broken since the foundry v12 update.
