### ISSUE TITLE
Tie rep values to IDs instead of directly to the ego

### ISSUE THREAD

**Issue by PhyDoesStuff** [Bubz43/ep2e#2]
There should be a way to track reputations across multiple identities. A character can theoretically a glitterati identity that has big f-rep while also publishing papers under an alias that has high r-rep (for whatever reason). Similarly, someone who works in the EPM and has high c-rep might want to keep their work with the Movement (and thus, their @-rep) more on the down-low with an alias.

**Comment by TheGam1ngWizard** [comment]
You can do this with reps (custom or not) using the 'fake id' item

**Comment by PhyDoesStuff** [comment]
Well, that would do it! Thanks for pointing out that item, it solves my needs.
